spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=talpets
spring.datasource.password=talpets
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml